development:
  adapter: redis
  url: redis://localhost:6379/

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:9dff88e397fe355ac082938ad06d19e6@grouper.redistogo.com:11325/
  channel_prefix: aspirinx_production
